export const LoanManagerABI = [
  {
    type: 'function',
    name: 'initializeLoan',
    inputs: [
      { name: 'projectId', type: 'uint256' },
      { name: 'monthlyPayment', type: 'uint256' },
      { name: 'termMonths', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'payMonthlyInstallment',
    inputs: [{ name: 'projectId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'checkDefaultStatus',
    inputs: [{ name: 'projectId', type: 'uint256' }],
    outputs: [{ name: 'isDefault', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'declareDefault',
    inputs: [{ name: 'projectId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'calculateEquitySplit',
    inputs: [{ name: 'projectId', type: 'uint256' }],
    outputs: [
      { name: 'hostPercent', type: 'uint256' },
      { name: 'investorPercent', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getCurrentMonth',
    inputs: [{ name: 'projectId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'projectLoans',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'projectId', type: 'uint256' },
      { name: 'monthlyPayment', type: 'uint256' },
      { name: 'termMonths', type: 'uint256' },
      { name: 'currentMonth', type: 'uint256' },
      { name: 'lastPaymentDate', type: 'uint256' },
      { name: 'nextPaymentDue', type: 'uint256' },
      { name: 'totalPaid', type: 'uint256' },
      { name: 'totalOwed', type: 'uint256' },
      { name: 'isDefaulted', type: 'bool' },
      { name: 'isCompleted', type: 'bool' },
      { name: 'initialized', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setRevenueDistributor',
    inputs: [{ name: '_distributor', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'LoanInitialized',
    inputs: [
      { name: 'projectId', type: 'uint256', indexed: true },
      { name: 'monthlyPayment', type: 'uint256', indexed: false },
      { name: 'termMonths', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PaymentReceived',
    inputs: [
      { name: 'projectId', type: 'uint256', indexed: true },
      { name: 'month', type: 'uint256', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DefaultDeclared',
    inputs: [
      { name: 'projectId', type: 'uint256', indexed: true },
      { name: 'missedMonth', type: 'uint256', indexed: false },
      { name: 'host', type: 'address', indexed: false },
    ],
    anonymous: false,
  },
] as const;
