export const MaintenanceDAOABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_solarProject', type: 'address' },
      { name: '_revenueDistributor', type: 'address' },
      { name: '_usdc', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitProposal',
    inputs: [
      { name: 'projectId', type: 'uint256' },
      { name: 'description', type: 'string' },
      { name: 'amount', type: 'uint256' },
      { name: 'vendor', type: 'address' },
    ],
    outputs: [{ name: 'proposalId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'castVote',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'support', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'executeProposal',
    inputs: [{ name: 'proposalId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getProposal',
    inputs: [{ name: 'proposalId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'proposalId', type: 'uint256' },
          { name: 'projectId', type: 'uint256' },
          { name: 'proposer', type: 'address' },
          { name: 'description', type: 'string' },
          { name: 'amount', type: 'uint256' },
          { name: 'vendor', type: 'address' },
          { name: 'votingDeadline', type: 'uint256' },
          { name: 'yesVotes', type: 'uint256' },
          { name: 'noVotes', type: 'uint256' },
          { name: 'executed', type: 'bool' },
          { name: 'passed', type: 'bool' },
          { name: 'status', type: 'uint8' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasVotedOnProposal',
    inputs: [
      { name: 'proposalId', type: 'uint256' },
      { name: 'voter', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getVotingPower',
    inputs: [
      { name: 'projectId', type: 'uint256' },
      { name: 'voter', type: 'address' },
    ],
    outputs: [{ name: 'votes', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proposalCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'VOTING_PERIOD',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'QUORUM_PERCENTAGE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ProposalSubmitted',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'projectId', type: 'uint256', indexed: true },
      { name: 'proposer', type: 'address', indexed: true },
      { name: 'description', type: 'string', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'vendor', type: 'address', indexed: false },
      { name: 'votingDeadline', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'VoteCast',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'voter', type: 'address', indexed: true },
      { name: 'support', type: 'bool', indexed: false },
      { name: 'votingPower', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ProposalExecuted',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'passed', type: 'bool', indexed: false },
      { name: 'yesVotes', type: 'uint256', indexed: false },
      { name: 'noVotes', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'FundsTransferred',
    inputs: [
      { name: 'proposalId', type: 'uint256', indexed: true },
      { name: 'vendor', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
] as const;