/**
 * Contract addresses loaded from backend/deployments/<chainId>.json.
 * This file is auto-generated by Deploy.s.sol — run `forge script` to update it.
 */
import localhost from "../../../backend/deployments/31337.json";

type AddressMap = {
  mockUSDC: `0x${string}`;
  hostReputation: `0x${string}`;
  solarProject: `0x${string}`;
  loanManager: `0x${string}`;
  revenueDistributor: `0x${string}`;
  maintenanceDAO: `0x${string}`;
  mockGridOracle: `0x${string}`;
  mockKeeper: `0x${string}`;
};

export const contracts: Record<string, AddressMap> = {
  localhost: localhost as AddressMap,
};
